import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function JSEssential() {
  return (
    <header className="bg-red-400 py-4">
      <div className="container mx-auto px-4">
        <nav className="flex items-center justify-between">
          <div className="flex items-center">
            <Link href="/destruct">Destructuring</Link>
          </div>
          <div>
            <Link href="/rest">rest</Link>
          </div>
          <div>
            <Link href="/spread">spread</Link>
          </div>
        </nav>
      </div>
    </header>
  );
}

function Navigation() {
  return (
    <header className="bg-green-400 py-4">
      <div className="container mx-auto px-4">
        <nav className="flex items-center justify-between">
          <div className="flex items-center">
            <Link href="/">Home</Link>
          </div>
          <div>
            <Link href="/getElementById">getElementById</Link>
          </div>
          <div>
            <Link href="/useState">useState</Link>
          </div>
          <div>
            <Link href="/useEffect">useEffect</Link>
          </div>
          <div>
            <Link href="/props">props</Link>
          </div>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <JSEssential />
        <Navigation />
        {children}
      </body>
    </html>
  );
}
